version: '3.8'

services:

  consul:
    image: hashicorp/consul:1.18
    ports:
      - '8204:8204'
    volumes:
      - ./config.json:/consul/config/config.json
    command: consul agent -dev -datacenter "dc-main" -bind "0.0.0.0" -config-file "/consul/config/config.json" -data-dir "/data" -log-level "DEBUG"
    networks:
      - consul

networks:
  consul:
    name: consul
    driver: bridge
