version: '3.8'

services:

  consul:
    image: hashicorp/consul:1.18
    ports:
      - '8500:8500'
      - '8204:8204'
    volumes:
      - ./config.json:/consul/config/config.json
      - consul_data:/data:rw
    command: 
      - consul 
      - agent 
      - -dev 
      - -datacenter 
      - "dc-main" 
      - -bind 
      - "0.0.0.0" 
      - -config-file 
      - "/consul/config/config.json" 
      - -log-level 
      - "DEBUG"
      - -advertise-wan
      - "10.0.0.4"
    networks:
      - consul

volumes:
  consul_data:

networks:
  consul:
    name: consul
    driver: bridge
