version: '3.8'

services:

  consul:
    image: hashicorp/consul:1.18
    ports:
      - '8500:8500'
      - '8304:8304/udp'
      - '8304:8304/tcp'
    volumes:
      - ./config.json:/consul/config/config.json
      - consul_data:/data:rw
    command: 
      - consul 
      - agent 
      - -bootstrap-expect=1
      - -config-file 
      - "/consul/config/config.json" 
    networks:
      - consul

volumes:
  consul_data:

networks:
  consul:
    name: consul
    driver: bridge
