version: '3.8'

services:

  consul:
    image: hashicorp/consul:1.18
    ports:
      - '8500:8500'
      # - '8304:8304/udp'
      # - '8304:8304/tcp'
    volumes:
      - ./config.json:/consul/config/config.json
    command: 
      - consul 
      - agent 
      - -config-file
      - "/consul/config/config.json" 
    networks:
      - consul

  consul-replicate:
    image: hashicorp/consul-replicate:0.4.0-alpine
    command: 
      - consul-replicate
      - -consul-addr
      - consul:8500
      - -prefix
      - "global@main-dc:backup"
      - -log-level 
      - "DEBUG"
    networks:
      - consul


networks:
  consul:
    name: consul
    driver: bridge
